# Generated by Django 2.2.3 on 2019-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('origin', models.CharField(max_length=20)),
                ('entry_type', models.CharField(max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
