# Generated by Django 2.2.3 on 2019-07-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
