# Generated by Django 2.2.3 on 2019-07-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0002_auto_20190716_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('E', 'I')], default='E', max_length=1),
        ),
    ]
