# Generated by Django 2.2.3 on 2019-07-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0003_auto_20190716_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], default='E', max_length=1),
        ),
    ]
