# Generated by Django 2.2.3 on 2019-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0004_auto_20190716_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
