# Generated by Django 2.2.3 on 2019-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finapp', '0005_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
